version: 0.0
os: windows
files:
  - source: /app.wsgi
    destination: /var/www/sample-app
  - source: /
    destination: /home/ec2-user/sample-app
  - source: /conf/sample_app.conf
    destination: /etc/httpd/conf.d
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
